source 'https://cdn.cocoapods.org/'

install! 'cocoapods',
         :generate_multiple_pod_projects => true,
         :incremental_installation => true

platform :ios, '12.0'

target 'KFSwiftImageLoader_Example' do
  pod 'KFSwiftImageLoader', :path => '../'
end
